# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title:               Qtae's Blog
tagline:             'I LOVE YA!'
description:         'HELLO WORLD'
url:                 http://qtae.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Qtae Kim
  url:               
  email:             qtkim91@gmail.com

# Custom vars
version:             1.0.0
